import { useState } from 'react';
import EducationBackButton from './EducationBackButton';
import './EducationSubscriptionPage.css';

const BENEFITS = ['Subscriber-only courses', 'Monthly webinars', 'Premium articles', 'Live class discounts', 'Early registration'];

export default function EducationSubscriptionPage({ educatorName = 'Jane Doe', subscribed, onBack, onSubscribe }) {
  const [billing, setBilling] = useState('monthly');
  const price = billing === 'monthly' ? '$19' : '$190';
  return <main className="esu-page"><EducationBackButton onClick={onBack} label="Back" /><div className="esu-layout"><section className="esu-info"><span className="esu-eyebrow">EDUCATOR SUBSCRIPTION</span><div className="esu-educator"><span>JD</span><div><b>{educatorName}</b><small>Education Subscription</small></div></div><h1>Learn more with<br/><em>{educatorName}</em></h1><p>Get ongoing access to {educatorName}'s subscriber education. This is an educator subscription, separate from KC's Free, Gold, and Platinum memberships.</p><div className="esu-separate-note"><span>↗</span><p><b>Independent educator access</b><br/>Your subscription supports {educatorName} and only covers education offered by this educator.</p></div></section><section className="esu-plan"><span className="esu-eyebrow">CHOOSE YOUR BILLING</span><div className="esu-billing"><button className={billing === 'monthly' ? 'active' : ''} onClick={() => setBilling('monthly')}>Monthly</button><button className={billing === 'yearly' ? 'active' : ''} onClick={() => setBilling('yearly')}>Yearly <i>Save $38</i></button></div><div className="esu-price"><b>{price}</b><span>/ {billing === 'monthly' ? 'month' : 'year'}</span></div><p className="esu-renewal">{billing === 'monthly' ? 'Billed monthly. Cancel any time.' : 'Billed annually. Equivalent to $15.83/month.'}</p><div className="esu-divider"/><h2>Includes</h2><ul>{BENEFITS.map(benefit => <li key={benefit}><span>✓</span>{benefit}</li>)}</ul><button className="esu-subscribe" onClick={onSubscribe}>{subscribed ? 'Subscribed ✓' : 'Subscribe'}</button>{subscribed && <div role="status" className="esu-success">Your {educatorName} education subscription is active in this demo.</div>}<small className="esu-footnote">This subscription is separate from KC membership and does not change your Free, Gold, or Platinum status.</small></section></div></main>;
}
