import { useState } from 'react';
import './EducatorEducationManagement.css';

const tabs = ['Published', 'Drafts', 'Under Review', 'Archived'];
const steps = ['Course Details', 'Modules', 'Lessons', 'Quiz/Assessment', 'Pricing', 'Access', 'Preview'];
const blankCourse = () => ({ title: '', description: '', category: 'Safety & Consent', level: 'Beginner', format: 'Course', modules: [], assessment: { enabled: true, type: 'Multiple choice', question: '', passingScore: '70' }, pricing: 'Free', price: '', access: 'All learners' });

export default function EducatorEducationManagement({ courses, onCoursesChange }) {
  const [activeTab, setActiveTab] = useState('Published');
  const [builderOpen, setBuilderOpen] = useState(false);
  const [step, setStep] = useState(0);
  const [course, setCourse] = useState(blankCourse());
  const [editingId, setEditingId] = useState(null);
  const [moduleTitle, setModuleTitle] = useState('');
  const [lessonTitle, setLessonTitle] = useState('');
  const [activeModule, setActiveModule] = useState(0);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');

  const update = values => setCourse(previous => ({ ...previous, ...values }));
  const startNew = () => { setCourse(blankCourse()); setEditingId(null); setStep(0); setError(''); setBuilderOpen(true); };
  const editDraft = item => { setCourse({ ...blankCourse(), ...item }); setEditingId(item.id); setStep(0); setError(''); setBuilderOpen(true); };
  const saveCourse = status => {
    const saved = { ...course, id: editingId || `educator-course-${Date.now()}`, status, updated: status === 'Under Review' ? 'Submitted for KC Admin review' : 'Saved as draft', learners: course.learners || 0 };
    onCoursesChange(previous => editingId ? previous.map(item => item.id === editingId ? saved : item) : [saved, ...previous]);
    setBuilderOpen(false);
    setError('');
    if (status === 'Under Review') setActiveTab('Under Review');
    setNotice(status === 'Under Review' ? 'Course submitted for KC Admin review. It is not public yet.' : 'Course draft saved.');
    window.setTimeout(() => setNotice(''), 4000);
  };
  const submitForReview = () => {
    if (!course.title.trim() || !course.description.trim()) { setStep(0); setError('Add a course title and description before submitting.'); return; }
    if (!course.modules.length || !course.modules.some(module => module.lessons?.length)) { setStep(1); setError('Add at least one module and one lesson before submitting.'); return; }
    saveCourse('Under Review');
  };
  const addModule = () => { if (!moduleTitle.trim()) return; update({ modules: [...course.modules, { title: moduleTitle.trim(), lessons: [] }] }); setModuleTitle(''); };
  const addLesson = () => { if (!lessonTitle.trim() || !course.modules[activeModule]) return; const modules = course.modules.map((module, index) => index === activeModule ? { ...module, lessons: [...(module.lessons || []), lessonTitle.trim()] } : module); update({ modules }); setLessonTitle(''); };
  const visibleCourses = courses.filter(item => item.status === activeTab);

  if (builderOpen) return <section className="eem-builder">
    <div className="eem-builder-head"><button onClick={() => setBuilderOpen(false)}>← My Education</button><div><span>COURSE BUILDER</span><h3>{editingId ? 'Edit course draft' : 'Create course'}</h3><p>Build the learning structure, review pricing and access, then send it to KC Admin.</p></div><button className="eem-save-draft" onClick={() => saveCourse('Draft')}>Save Draft</button></div>
    <ol className="eem-stepper">{steps.map((label, index) => <li key={label} className={`${step === index ? 'active' : ''} ${step > index ? 'done' : ''}`}><button onClick={() => { setStep(index); setError(''); }}><span>{step > index ? '✓' : index + 1}</span><b>{label}</b></button></li>)}</ol>
    {error && <div className="eem-error" role="alert">{error}</div>}
    <div className="eem-step-panel">
      {step === 0 && <><span className="eem-step-kicker">01 · COURSE DETAILS</span><h2>Set up the basics</h2><div className="eem-fields"><label>Course title<input value={course.title} onChange={event => update({ title: event.target.value })} placeholder="e.g. Consent Foundations" /></label><label>Category<select value={course.category} onChange={event => update({ category: event.target.value })}>{['Safety & Consent', 'Communication', 'Rope', 'Power Exchange', 'Sensation', 'Other'].map(value => <option key={value}>{value}</option>)}</select></label><label>Level<select value={course.level} onChange={event => update({ level: event.target.value })}>{['Beginner', 'Intermediate', 'Advanced', 'All levels'].map(value => <option key={value}>{value}</option>)}</select></label><label>Format<select value={course.format} onChange={event => update({ format: event.target.value })}>{['Course', 'Webinar', 'Workshop', 'Recorded class'].map(value => <option key={value}>{value}</option>)}</select></label><label className="eem-wide">Description<textarea rows="4" value={course.description} onChange={event => update({ description: event.target.value })} placeholder="What will learners explore and take away?" /></label></div></>}
      {step === 1 && <><span className="eem-step-kicker">02 · MODULES</span><h2>Organize the course</h2><p className="eem-help">Modules group related lessons into a clear learning journey.</p><div className="eem-add-row"><input value={moduleTitle} onChange={event => setModuleTitle(event.target.value)} onKeyDown={event => event.key === 'Enter' && (event.preventDefault(), addModule())} placeholder="Module name, e.g. Foundations"/><button onClick={addModule}>＋ Add Module</button></div><div className="eem-structure-list">{course.modules.map((module, index) => <div key={`${module.title}-${index}`}><span>{String(index + 1).padStart(2, '0')}</span><b>{module.title}</b><small>{module.lessons?.length || 0} lessons</small><button onClick={() => update({ modules: course.modules.filter((_, i) => i !== index) })}>Remove</button></div>)}</div>{!course.modules.length && <div className="eem-empty-inline">No modules yet. Add the first module above.</div>}</>}
      {step === 2 && <><span className="eem-step-kicker">03 · LESSONS</span><h2>Add lessons to your modules</h2><p className="eem-help">Lessons sit inside a module. Add a title for each lesson; lesson content can be added in the course builder.</p>{course.modules.length ? <><label className="eem-module-select">Choose a module<select value={activeModule} onChange={event => setActiveModule(Number(event.target.value))}>{course.modules.map((module, index) => <option key={`${module.title}-${index}`} value={index}>{module.title}</option>)}</select></label><div className="eem-add-row"><input value={lessonTitle} onChange={event => setLessonTitle(event.target.value)} onKeyDown={event => event.key === 'Enter' && (event.preventDefault(), addLesson())} placeholder="Lesson title"/><button onClick={addLesson}>＋ Add Lesson</button></div><div className="eem-structure-list">{(course.modules[activeModule]?.lessons || []).map((lesson, index) => <div key={`${lesson}-${index}`}><span>{index + 1}</span><b>{lesson}</b><small>Lesson</small><button onClick={() => update({ modules: course.modules.map((module, i) => i === activeModule ? { ...module, lessons: module.lessons.filter((_, lessonIndex) => lessonIndex !== index) } : module) })}>Remove</button></div>)}</div></> : <div className="eem-empty-inline">Add a module before adding lessons.</div>}</>}
      {step === 3 && <><span className="eem-step-kicker">04 · QUIZ / ASSESSMENT</span><h2>Check learner understanding</h2><label className="eem-check"><input type="checkbox" checked={course.assessment.enabled} onChange={event => update({ assessment: { ...course.assessment, enabled: event.target.checked } })}/> Include an assessment</label>{course.assessment.enabled && <div className="eem-fields"><label>Assessment type<select value={course.assessment.type} onChange={event => update({ assessment: { ...course.assessment, type: event.target.value } })}>{['Multiple choice', 'Multiple answer', 'True / false'].map(value => <option key={value}>{value}</option>)}</select></label><label>Passing score (%)<input type="number" min="1" max="100" value={course.assessment.passingScore} onChange={event => update({ assessment: { ...course.assessment, passingScore: event.target.value } })}/></label><label className="eem-wide">Sample question<input value={course.assessment.question} onChange={event => update({ assessment: { ...course.assessment, question: event.target.value } })} placeholder="Add a question or leave this for later"/></label></div>}</>}
      {step === 4 && <><span className="eem-step-kicker">05 · PRICING</span><h2>Choose how learners access pricing</h2><div className="eem-choice-grid">{['Free', 'Paid'].map(value => <button key={value} className={course.pricing === value ? 'selected' : ''} onClick={() => update({ pricing: value })}><b>{value}</b><small>{value === 'Free' ? 'Available at no cost' : 'Set a one-time course price'}</small></button>)}</div>{course.pricing === 'Paid' && <label className="eem-price-field">Price<input type="number" min="0" step="0.01" value={course.price} onChange={event => update({ price: event.target.value })} placeholder="0.00"/></label>}</>}
      {step === 5 && <><span className="eem-step-kicker">06 · ACCESS</span><h2>Set the learner access rule</h2><p className="eem-help">Membership or purchase requirements can be reviewed with your submission.</p><div className="eem-access-options">{['All learners', 'Gold membership', 'Platinum membership', 'Purchase required', 'Educator subscription'].map(value => <label key={value} className={course.access === value ? 'selected' : ''}><input type="radio" name="course-access" checked={course.access === value} onChange={() => update({ access: value })}/><span><b>{value}</b><small>{value === 'All learners' ? 'No membership restriction' : 'Only eligible learners can start'}</small></span></label>)}</div></>}
      {step === 6 && <><span className="eem-step-kicker">07 · PREVIEW</span><h2>Review your course</h2><div className="eem-preview"><div className="eem-preview-cover">{course.category}</div><div className="eem-preview-content"><div className="eem-preview-badges"><span>{course.format}</span><span>{course.level}</span><span>{course.pricing === 'Paid' ? `$${course.price || '0.00'}` : 'Free'}</span></div><h3>{course.title || 'Course title'}</h3><p>{course.description || 'Your course description will appear here.'}</p><small>{course.access} · {course.modules.length} modules · {course.modules.reduce((total, module) => total + (module.lessons?.length || 0), 0)} lessons</small></div></div><div className="eem-review-callout"><b>After you submit</b><p>Your course will move to <strong>Under Review</strong> for KC Admin moderation. It will not be published or visible to learners until approved.</p></div></>}
    </div>
    <footer className="eem-builder-footer"><button disabled={step === 0} onClick={() => { setStep(previous => Math.max(0, previous - 1)); setError(''); }}>← Previous</button><span>Step {step + 1} of {steps.length}</span>{step < steps.length - 1 ? <button className="eem-next" onClick={() => { setStep(previous => Math.min(steps.length - 1, previous + 1)); setError(''); }}>Next</button> : <button className="eem-submit" onClick={submitForReview}>Submit for Review</button>}</footer>
  </section>;

  return <section className="eem-management"><div className="eem-management-heading"><div><span className="eem-step-kicker">EDUCATION MANAGEMENT</span><h3>My Education</h3><p>Manage your courses and track each course’s review status.</p></div><button className="ed-primary" onClick={startNew}>＋ Create Course</button></div><nav className="eem-tabs">{tabs.map(tab => <button className={activeTab === tab ? 'active' : ''} key={tab} onClick={() => setActiveTab(tab)}>{tab}<span>{courses.filter(item => item.status === tab).length}</span></button>)}</nav>{activeTab === 'Under Review' && <div className="eem-review-callout eem-review-inline"><b>KC Admin review</b><p>Submitted courses stay private while the admin team reviews course structure, content, pricing, and access. Approval is required before publishing.</p></div>}{visibleCourses.length ? <div className="eem-course-list">{visibleCourses.map(item => <article className="eem-course-card" key={item.id || item.title}><div className="eem-course-symbol">{(item.category || 'E').slice(0,1)}</div><div className="eem-course-main"><div className="eem-course-title-line"><h4>{item.title}</h4><span className={`eem-status eem-status-${item.status.toLowerCase().replace(/\s+/g, '-')}`}>{item.status}</span></div><p>{item.description || item.category} · {item.level || 'All levels'} · {item.modules?.length || 0} modules</p><small>{item.updated || 'Course in your educator library'}</small></div><div className="eem-course-actions">{item.status === 'Draft' && <button onClick={() => editDraft(item)}>Continue editing</button>}{item.status === 'Under Review' && <span>Awaiting admin review</span>}{item.status === 'Published' && <button onClick={() => onCoursesChange(previous => previous.map(courseItem => courseItem === item ? { ...courseItem, status: 'Archived' } : courseItem))}>Archive</button>}{item.status === 'Archived' && <button onClick={() => onCoursesChange(previous => previous.map(courseItem => courseItem === item ? { ...courseItem, status: 'Draft' } : courseItem))}>Restore to drafts</button>}</div></article>)}</div> : <div className="eem-empty"><span>▣</span><b>No {activeTab.toLowerCase()} courses yet</b><p>{activeTab === 'Drafts' ? 'Save a course draft to continue building it later.' : activeTab === 'Under Review' ? 'Courses submitted to KC Admin will appear here.' : activeTab === 'Archived' ? 'Archived courses will be kept here.' : 'Create your first course to start building education.'}</p>{activeTab === 'Published' && <button onClick={startNew}>＋ Create Course</button>}</div>}{notice && <div className="eem-toast" role="status">{notice}<button onClick={() => setNotice('')}>×</button></div>}</section>;
}
